import type { TableColumn } from "@moritzbrantner/tables";
import { Badge, type BadgeProps } from "../demo-ui";

import {
  auditActions,
  auditStatuses,
  billingCycles,
  countries,
  customerSuccess,
  formatCurrency,
  formatDate,
  formatPercent,
  healthValues,
  owners,
  plans,
  productFitValues,
  regions,
  segments,
  stages,
  statuses,
} from "./data";
import type { AuditRow, CustomerRow, PipelineRow } from "./model";

export const pipelineColumns: TableColumn<PipelineRow>[] = [
  { accessor: "id", header: "ID", id: "id", sortable: true, type: "string", width: 116 },
  {
    accessor: "account",
    header: "Account",
    id: "account",
    sortable: true,
    type: "string",
    width: 240,
  },
  {
    accessor: "owner",
    filterOptions: owners,
    header: "Owner",
    id: "owner",
    sortable: true,
    type: "string",
    width: 144,
  },
  {
    accessor: "region",
    filterOptions: regions,
    header: "Region",
    id: "region",
    sortable: true,
    type: "string",
    width: 148,
  },
  {
    accessor: "segment",
    filterOptions: segments,
    header: "Segment",
    id: "segment",
    sortable: true,
    type: "string",
    width: 152,
  },
  {
    accessor: "stage",
    filterOptions: stages,
    header: "Stage",
    id: "stage",
    sortable: true,
    type: "string",
    width: 148,
  },
  {
    accessor: "amount",
    align: "end",
    cell: (value) => formatCurrency(Number(value)),
    header: "Amount",
    id: "amount",
    sortable: true,
    type: "number",
    width: 144,
  },
  {
    accessor: "probability",
    align: "end",
    cell: (value) => formatPercent(Number(value)),
    header: "Probability",
    id: "probability",
    sortable: true,
    type: "number",
    width: 136,
  },
  {
    accessor: "health",
    cell: (value) => <StatusBadge value={String(value)} />,
    filterOptions: healthValues,
    header: "Health",
    id: "health",
    sortable: true,
    type: "string",
    width: 136,
  },
  {
    accessor: "updatedAt",
    cell: (value) => (value instanceof Date ? formatDate(value) : ""),
    header: "Updated",
    id: "updatedAt",
    sortAccessor: (row) => row.updatedAt,
    sortable: true,
    type: "date",
    width: 148,
  },
  {
    accessor: "renewalDate",
    cell: (value) => (value instanceof Date ? formatDate(value) : ""),
    header: "Renewal",
    id: "renewalDate",
    sortAccessor: (row) => row.renewalDate,
    sortable: true,
    type: "date",
    width: 148,
  },
];

export const customerColumns: TableColumn<CustomerRow>[] = [
  { accessor: "id", header: "ID", id: "id", sortable: true, type: "string", width: 112 },
  {
    accessor: "account",
    header: "Account",
    id: "account",
    sortable: true,
    type: "string",
    width: 240,
  },
  {
    accessor: "status",
    cell: (value) => <StatusBadge value={String(value)} />,
    filterOptions: statuses,
    header: "Status",
    id: "status",
    sortable: true,
    type: "string",
    width: 132,
  },
  {
    accessor: "plan",
    filterOptions: plans,
    header: "Plan",
    id: "plan",
    sortable: true,
    type: "string",
    width: 128,
  },
  {
    accessor: "segment",
    filterOptions: segments,
    header: "Segment",
    id: "segment",
    sortable: true,
    type: "string",
    width: 152,
  },
  {
    accessor: "region",
    filterOptions: regions,
    header: "Region",
    id: "region",
    sortable: true,
    type: "string",
    width: 152,
  },
  {
    accessor: "country",
    filterOptions: countries,
    header: "Country",
    id: "country",
    sortable: true,
    type: "string",
    width: 164,
  },
  {
    accessor: "owner",
    filterOptions: owners,
    header: "Owner",
    id: "owner",
    sortable: true,
    type: "string",
    width: 136,
  },
  {
    accessor: "csm",
    filterOptions: customerSuccess,
    header: "CSM",
    id: "csm",
    sortable: true,
    type: "string",
    width: 136,
  },
  {
    accessor: "arr",
    align: "end",
    cell: (value) => formatCurrency(Number(value)),
    header: "ARR",
    id: "arr",
    sortable: true,
    type: "number",
    width: 132,
  },
  {
    accessor: "contractValue",
    align: "end",
    cell: (value) => formatCurrency(Number(value)),
    header: "Contract",
    id: "contractValue",
    sortable: true,
    type: "number",
    width: 144,
  },
  {
    accessor: "seats",
    align: "end",
    header: "Seats",
    id: "seats",
    sortable: true,
    type: "number",
    width: 112,
  },
  {
    accessor: "activeUsers",
    align: "end",
    header: "Active users",
    id: "activeUsers",
    sortable: true,
    type: "number",
    width: 136,
  },
  {
    accessor: "usage",
    align: "end",
    cell: (value) => formatPercent(Number(value)),
    header: "Usage",
    id: "usage",
    sortable: true,
    type: "number",
    width: 116,
  },
  {
    accessor: "riskScore",
    align: "end",
    cell: (value) => `${Number(value)}/100`,
    header: "Risk",
    id: "riskScore",
    sortable: true,
    type: "number",
    width: 104,
  },
  {
    accessor: "openTickets",
    align: "end",
    header: "Tickets",
    id: "openTickets",
    sortable: true,
    type: "number",
    width: 112,
  },
  {
    accessor: "billingCycle",
    filterOptions: billingCycles,
    header: "Billing",
    id: "billingCycle",
    sortable: true,
    type: "string",
    width: 128,
  },
  {
    accessor: "productFit",
    filterOptions: productFitValues,
    header: "Fit",
    id: "productFit",
    sortable: true,
    type: "string",
    width: 112,
  },
  {
    accessor: "renewalDate",
    cell: (value) => (value instanceof Date ? formatDate(value) : ""),
    header: "Renewal",
    id: "renewalDate",
    sortAccessor: (row) => row.renewalDate,
    sortable: true,
    type: "date",
    width: 148,
  },
  {
    accessor: "lastLoginAt",
    cell: (value) => (value instanceof Date ? formatDate(value) : ""),
    header: "Last login",
    id: "lastLoginAt",
    sortAccessor: (row) => row.lastLoginAt,
    sortable: true,
    type: "date",
    width: 148,
  },
];

export const auditColumns: TableColumn<AuditRow>[] = [
  { accessor: "id", header: "ID", id: "id", sortable: true, type: "string", width: 112 },
  {
    accessor: "resource",
    header: "Resource",
    id: "resource",
    sortable: true,
    type: "string",
    width: 240,
  },
  {
    accessor: "actor",
    filterOptions: owners,
    header: "Actor",
    id: "actor",
    sortable: true,
    type: "string",
    width: 144,
  },
  {
    accessor: "action",
    filterOptions: auditActions,
    header: "Action",
    id: "action",
    sortable: true,
    type: "string",
    width: 136,
  },
  {
    accessor: "status",
    cell: (value) => <StatusBadge value={String(value)} />,
    filterOptions: auditStatuses,
    header: "Status",
    id: "status",
    sortable: true,
    type: "string",
    width: 132,
  },
  {
    accessor: "occurredAt",
    cell: (value) => (value instanceof Date ? formatDate(value) : ""),
    header: "Occurred",
    id: "occurredAt",
    sortAccessor: (row) => row.occurredAt,
    sortable: true,
    type: "date",
    width: 148,
  },
];

function StatusBadge({ value }: { value: string }) {
  return <Badge variant={getStatusVariant(value)}>{value}</Badge>;
}

function getStatusVariant(value: string): BadgeProps["variant"] {
  if (["At risk", "Failed", "Low", "Paused"].includes(value)) {
    return "destructive";
  }

  if (["Healthy", "Active", "Expanding", "Succeeded", "High"].includes(value)) {
    return "default";
  }

  return "secondary";
}
